language: node_js
node_js:
- '6'
notifications:
  slack:
    secure: IOyahUWqMYE++fxwUSPCneTbyrUV+l4rhNiSuYG3876GHS05pXSNGx/akyd7RKEfJ6vAI3OlNrnsenkK8XZiDG74lFWusr6VnbYn0qgvmfg5FuGm2UWB2E6BAAd7g/rL9X2z4yHu3botkSDa/jQgkUwFajGuwWwCoujG9A6oVArNlQE8L266+C6/sCtwNF1BpIQKGOUDyX+vlqoD5SblvDmr4iCdPU8c7fKVEhSwbhrhqDSalVg5WliMGIyOq1NWR1LWtpq8PUgsH9XoafFFQzAxdSevXSHqAAmJBf9R06tq9IKEWt8SSidaE4jQndu7tdTpUxHfHnrKnonMb6wmnL172RO3GWbflYHn/2//BkMVAaB+QFnwAlNsjYOa5//mCAzJ6ajfW2P95dJpJOwpKvCo0ISAXaOXm5tvwIV2EdrFXt9jXNGpxLJdv9tEhxze/d0sXhDs8ntur7F2H68fkRdtgO2Upbm9GfcJ5ZieFOvInSszjiLrTY3oy4U+IePJhewGpNlKAkqU1HdllnzzNkt4MPYMyMXPlX9Sp9yNWiA8KXPxpVjKCv/nPHqL2Y20l3bWFe5+9DtKhur7C7gxE0u85Xbqp7UqxlMzHMW/Rn3tK9MHalGqVw8XXWQfmARkjobjR8qEE9RQwNHKKlQciWXl+7QbGUDszCPvTdfKPZI=
